src/main/java/id/go/menlhk/bp2sdm/spjk/domain/User.java
package id.go.menlhk.bp2sdm.spjk.domain;

import java.util.Date;

public class User {
	private String id;
	private String firstName;
	private String lastName;
	private String username;
	private String password;
	private String currentPassword;
	private String description;
	private String token;
	private Date expired;
	private String role;
	private String position;
	private String namePosition;
	private String userId;
	private String email;

	public User() {

	}

	public User(String id) {
		this.id = id;
	}

	public String getName() {
		return firstName + " " + lastName;
	}

	public String getNamePosition() {
		return namePosition;
	}

	public User(String id, String firstName, String lastName, String username, String password, String currentPassword,
			String description, String token, Date expired, String role, String position, String email) {
		super();
		this.id = id;
		this.firstName = firstName;
		this.lastName = lastName;
		this.username = username;
		this.password = password;
		this.currentPassword = currentPassword;
		this.description = description;
		this.token = token;
		this.expired = expired;
		this.role = role;
		this.position = position;
		this.email = email;
	}

	public String getId() {
		return id;
	}

	public String getUserId() {
		return userId;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getFirstName() {
		return firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getLastName() {
		return lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public String getUsername() {
		return username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getCurrentPassword() {
		return currentPassword;
	}

	public void setCurrentPassword(String currentPassword) {
		this.currentPassword = currentPassword;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getToken() {
		return token;
	}

	public void setToken(String token) {
		this.token = token;
	}

	public Date getExpired() {
		return expired;
	}

	public void setExpired(Date expired) {
		this.expired = expired;
	}

	public String getRole() {
		return role;
	}

	public void setRole(String role) {
		this.role = role;
	}

	public String getPosition() {
		return position;
	}

	public void setPosition(String position) {
		this.position = position;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	private String tem_password;

	public String getTem_password() {
		return tem_password;
	}

	public void setTem_password(String tem_password) {
		this.tem_password = tem_password;
	}

}

src/main/java/id/go/menlhk/bp2sdm/spjk/controllers/SimulasiUjianController.java
package id.go.menlhk.bp2sdm.spjk.controllers;

import static org.mockito.Matchers.intThat;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.forwardedUrl;

import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.StringJoiner;
import java.util.Timer;
import java.util.TimerTask;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpSession;

import org.apache.commons.io.FilenameUtils;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.format.annotation.DateTimeFormat;
import org.springframework.http.HttpRequest;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.scheduling.annotation.Scheduled;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.security.oauth2.provider.OAuth2Authentication;
import org.springframework.transaction.annotation.Propagation;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

import id.go.menlhk.bp2sdm.spjk.core.QueryParameter;
import id.go.menlhk.bp2sdm.spjk.domain.Config;
import id.go.menlhk.bp2sdm.spjk.domain.MappingJabatanUnitAuditi;
import id.go.menlhk.bp2sdm.spjk.domain.Pertanyaan;
import id.go.menlhk.bp2sdm.spjk.domain.PertanyaanJawaban;
import id.go.menlhk.bp2sdm.spjk.domain.Sesi;
import id.go.menlhk.bp2sdm.spjk.domain.User;
import id.go.menlhk.bp2sdm.spjk.domain.UserPertanyaan;
import id.go.menlhk.bp2sdm.spjk.domain.UserPertanyaanJawaban;
import id.go.menlhk.bp2sdm.spjk.domain.UserResponden;
import id.go.menlhk.bp2sdm.spjk.domain.bc.OauthUserOrganization;
import id.go.menlhk.bp2sdm.spjk.domain.bc.PernyataanJawaban;
import id.go.menlhk.bp2sdm.spjk.helper.ResponseWrapper;
import id.go.menlhk.bp2sdm.spjk.helper.ResponseWrapperList;
import id.go.menlhk.bp2sdm.spjk.common.Utils;
import id.go.menlhk.bp2sdm.spjk.mapper.ConfigMapper;
import id.go.menlhk.bp2sdm.spjk.mapper.MappingJabatanUnitAuditiMapper;
import id.go.menlhk.bp2sdm.spjk.mapper.PertanyaanJawabanMapper;
import id.go.menlhk.bp2sdm.spjk.mapper.PertanyaanMapper;
import id.go.menlhk.bp2sdm.spjk.mapper.SesiMapper;
import id.go.menlhk.bp2sdm.spjk.mapper.UserPertanyaanJawabanMapper;
import id.go.menlhk.bp2sdm.spjk.mapper.UserPertanyaanMapper;
import id.go.menlhk.bp2sdm.spjk.mapper.UserRespondenMapper;
import id.go.menlhk.bp2sdm.spjk.ref.AccountLoginInfo;

@RestController
@RequestMapping("/simulasi-survey")
public class SimulasiUjianController extends BaseController {


	@Autowired
	private PertanyaanMapper pertanyaanMapper;
	
	@Autowired
	private PertanyaanJawabanMapper pertanyaanJawabanMapper;

	@Autowired
	private UserPertanyaanMapper userPertanyaanMapper;

	@Autowired
	private UserPertanyaanJawabanMapper userPertanyaanJawabanMapper;

	@Autowired
	private UserRespondenMapper userRespondenMapper;

	@Autowired
	private ConfigMapper configMapper;

	@Autowired
	private SesiMapper sesiMapper;
	
	public String idResponden;
    

	@Autowired
	private MappingJabatanUnitAuditiMapper mappingJabatanUnitAuditiMapper;
	
	@RequestMapping(value = "/check-responden/{id}", method = RequestMethod.GET, produces = "application/json")
	public ResponseEntity<ResponseWrapper> getById(@PathVariable String id, HttpServletRequest request, HttpSession session) throws Exception {
		ResponseWrapper resp = new id.go.menlhk.bp2sdm.spjk.helper.ResponseWrapper();
		UserResponden data = userRespondenMapper.checkRespondenDataGeneral(id);
		resp.setData(data);
		return new ResponseEntity<ResponseWrapper>(resp, HttpStatus.valueOf(resp.getCode()));
	}
	//
	@RequestMapping(value = "/update-status-soal", method = RequestMethod.GET, produces = "application/json")
	@Transactional(rollbackFor = Exception.class, propagation = Propagation.REQUIRED)
	public ResponseEntity<id.go.menlhk.bp2sdm.spjk.helper.ResponseWrapper> updateStatusSoal(
			@RequestParam("id") Optional<String> id,
			@RequestParam("mark") Optional<String> mark,
			@RequestParam("jenis") Optional<String> jenis,
			@RequestParam("durasi") Optional<Integer> durasi, HttpSession session,
			HttpServletRequest request, Model model) throws Exception {
		ResponseWrapper resp = new ResponseWrapper();
		if(!isTokenValid(request)) { 
			resp.setCode(HttpStatus.UNAUTHORIZED.value());
			resp.setMessage("Sesi Login anda telah habis/Anda telah melakukan login pada device yang lain.");
			return new ResponseEntity<ResponseWrapper>(resp, HttpStatus.valueOf(resp.getCode()));
		}
		UserPertanyaan data = userPertanyaanMapper.getEntityNormal(id.get());
		if(data==null) {
			resp.setCode(HttpStatus.BAD_REQUEST.value());
			resp.setMessage("Data tidak ditemukan.");
			return new ResponseEntity<ResponseWrapper>(resp, HttpStatus.valueOf(resp.getCode()));
		}
		
		QueryParameter param = new QueryParameter();
		param.setClause(param.getClause()+" AND "+UserPertanyaan.ID_RESPONDEN+" ='"+data.getIdResponden()+"'");
		param.setClause(param.getClause()+" AND "+UserPertanyaan.STATUS+" ='"+1+"'");
		List<UserPertanyaan> dataNow = userPertanyaanMapper.getList(param);
		if(data.getJenisKompetensi().equals(dataNow.get(0).getJenisKompetensi())) {
			data = dataNow.get(0);
		}else {
			resp.setCode(HttpStatus.NOT_ACCEPTABLE.value());
			resp.setMessage("Seharusnya Kompetensi anda adalah:<strong>"+dataNow.get(0).getJenisKompetensi()+"</strong> bukan <strong>"+data.getJenisKompetensi()+"</strong> , Silahkan refresh halaman anda untuk melanjutkan, atau klik <a href='javascript:void(0)' onclick='window.location.reload()'>disini</a>.");
			return new ResponseEntity<ResponseWrapper>(resp, HttpStatus.valueOf(resp.getCode()));
		}
		
		Integer nosoal = 0;
		if(mark.isPresent()) nosoal = Integer.valueOf(mark.get());
		if(data.getNo() > nosoal) {
			resp.setCode(HttpStatus.NOT_ACCEPTABLE.value());
			resp.setMessage("Nomor Soal tidak sesuai, anda seharusnya berada di nomor:<strong>"+data.getNo()+"</strong>, Silahkan refresh halaman anda untuk melanjutkan, atau klik <a href='javascript:void(0)' onclick='window.location.reload()'>disini</a>.");
			return new ResponseEntity<ResponseWrapper>(resp, HttpStatus.valueOf(resp.getCode()));
		}
		
		if(mark.isPresent()){
			data.setStatus(null);
			userPertanyaanMapper.updateStatus(data);
			
			param = new QueryParameter();
			param.setClause(param.getClause()+" AND "+UserPertanyaan.ID_RESPONDEN+" ='"+data.getIdResponden()+"'");
			param.setClause(param.getClause()+" AND "+UserPertanyaan.NO+" ='"+(data.getNo()+1)+"'");
			param.setClause(param.getClause()+" AND "+UserPertanyaan.JENIS_KOMPETENSI+" ='"+data.getJenisKompetensi()+"'");
			if(userPertanyaanMapper.getCount(param) > 1) {
				resp.setCode(HttpStatus.BAD_REQUEST.value());
				resp.setMessage("Jika pesan ini muncul, laporakan ke admin.");
				return new ResponseEntity<ResponseWrapper>(resp, HttpStatus.valueOf(resp.getCode()));
			}
			UserPertanyaan userPertanyaan = userPertanyaanMapper.getList(param).get(0);
			userPertanyaan.setStatus("1");
			userPertanyaanMapper.updateStatus(userPertanyaan);
			
			UserResponden ur = userRespondenMapper.checkRespondenDataGeneral(data.getIdResponden());
			if(ur.getStatus().equals("")) {
				ur.setStatus("PROSES");
				userRespondenMapper.update(ur);
			}
		}
		return new ResponseEntity<id.go.menlhk.bp2sdm.spjk.helper.ResponseWrapper>(resp, HttpStatus.valueOf(resp.getCode()));
	}
	
	@RequestMapping(value = "/update-durasi-soal", method = RequestMethod.GET, produces = "application/json")
	@Transactional(rollbackFor = Exception.class, propagation = Propagation.REQUIRED)
	public ResponseEntity<id.go.menlhk.bp2sdm.spjk.helper.ResponseWrapper> updateDurasiSoal(
			@RequestParam("id") Optional<String> id,
			@RequestParam("mark") Optional<String> mark,
			@RequestParam("jenis") Optional<String> jenis,
			@RequestParam("durasi") Optional<Integer> durasi, HttpSession session,
			HttpServletRequest request, Model model) throws Exception {
		ResponseWrapper resp = new ResponseWrapper();
		
		UserPertanyaan data = userPertanyaanMapper.getEntityNormal(id.get());
		data.setDurasiBerjalan(data.getDurasi()-durasi.get());
		userPertanyaanMapper.updateDurasi(data);
		
		return new ResponseEntity<id.go.menlhk.bp2sdm.spjk.helper.ResponseWrapper>(resp, HttpStatus.valueOf(resp.getCode()));
	}
	@RequestMapping(value = "/update-status-responden", method = RequestMethod.GET, produces = "application/json")
	@Transactional(rollbackFor = Exception.class, propagation = Propagation.REQUIRED)
	public ResponseEntity<id.go.menlhk.bp2sdm.spjk.helper.ResponseWrapper> updateStatusResponden(
			@RequestParam("id") Optional<String> id, HttpSession session,
			HttpServletRequest request, Model model) throws Exception {
		ResponseWrapper resp = new ResponseWrapper();

		if(!isTokenValid(request)) { 
			resp.setCode(HttpStatus.UNAUTHORIZED.value());
			resp.setMessage("Sesi Login anda telah habis/Anda telah melakukan login pada device yang lain.");
			return new ResponseEntity<ResponseWrapper>(resp, HttpStatus.valueOf(resp.getCode()));
		}

		UserResponden data = userRespondenMapper.getEntity(id.get());
		data.setStatus("PROSES");
		userRespondenMapper.update(data);
		
		resp.setData(data);
		return new ResponseEntity<id.go.menlhk.bp2sdm.spjk.helper.ResponseWrapper>(resp, HttpStatus.valueOf(resp.getCode()));
	}
	//
	@RequestMapping(value = "/", method = RequestMethod.GET, produces = "application/json")

src/main/webapp/WEB-INF/jsp/pages/user/index.jsp
<%@ taglib prefix="fn" uri="http://java.sun.com/jsp/jstl/functions"%>
<%@page import="java.util.Map"%>
<%@include file="inc/redirect.jsp"%>

<!DOCTYPE html>
<html lang="en">

<head>
	<%@include file="inc/header.jsp"%>
	<script>
	function init(){}
	var user_id = "<%= request.getAttribute("userId") %>";
	var sesi_id = "${requestScope.idSesi}";
	var responden_id = "${requestScope.idResponden}";
	</script>
	<style>
	.swal2-content{text-align:left!important}
	</style>
</head>

<body>
	<%@include file="inc/navbar.jsp"%>

    <div class="container ">
      <div class="row justify-content-center pt-5">
        <div class="col-md-9">
       <c:choose>
         <c:when test = "${requestScope.statusUnitKompResponden == 'TEKNIS_INTI' || requestScope.statusUnitKompResponden == 'TEKNIS_PILIHAN'}">
         	<c:redirect url="/page/main-unit-kompetensi?mode=teknis"/>
         </c:when>
         <c:when test = "${requestScope.statusUnitKompResponden == 'MANAJERIAL'}">
         	<c:redirect url="/page/main-unit-kompetensi?mode=manajerial"/>
         </c:when>
         <c:when test = "${requestScope.statusUnitKompResponden == 'SOSIOKULTURAL'}">
         	<c:redirect url="/page/main-unit-kompetensi?mode=sosiokultural"/>
         </c:when>
         <c:when test = "${requestScope.statusResponden == 'PROSES'}">
         	<c:redirect url="/page/simulasi-ujian"/>
         </c:when>
         <c:when test = "${requestScope.statusUnitKompResponden==null && requestScope.statusResponden == 'SELESAI'}">
	        <div class="card mb-3">
			    <div id="msg-survey" class="card-body"><h4>Terimakasih Atas Partisipasi Anda.</h4></div>
			</div>
         </c:when>
         <c:when test = "${requestScope.statusResponden == 'NO_SESI'}">
	        <div class="card mb-3">
			    <div id="msg-survey" class="card-body"><h4>Tidak ada kegiatan <strong>ujian</strong>, atau mohon laporkan admin jika anda merasa sedang ada kegiatan ujian, </br> Terima Kasih</h4></div>
			</div>
			<p class="mt-5 h5">Quick Access</p>
			<div class="card border-0">
			    <!-- <button class=" btn btn-info btn-lg btn-block">PEMETAAAN</button> -->
			    <a class="btn btn-info btn-lg btn-block" href="${pageContext.request.contextPath}/page/dashboard?mode=profile&"><i class="fas fa-fw fa-tachometer-alt"></i> DASHBOARD PEMETAAN</a>
			</div>
         </c:when>
         <c:when test = "${requestScope.statusResponden == 'NO_SESI_JABATAN'}">
	        <div class="card mb-3">
			    <div id="msg-survey" class="card-body"><h5>Sistem tidak dapat menemukan user anda sebagai peserta ujian, <br/><br/> Terima Kasih</h5></div>
			</div>
			
			<p class="mt-5 h5">Quick Access</p>
			<div class="card ">
			    <!-- <button class=" btn btn-info btn-lg btn-block">PEMETAAAN</button> -->
			    <a class="btn btn-info btn-lg btn-block" href="${pageContext.request.contextPath}/page/dashboard?mode=profile&"><i class="fas fa-fw fa-tachometer-alt"></i> DASHBOARD PEMETAAN</a>
			</div>
         </c:when>
         <c:when test = "${requestScope.statusResponden == 'NO_SIMPEG'}">
	        <div class="card mb-3">
			    <div id="msg-survey" class="card-body"><h5>Mohon Maaf, server tidak mendeteksi NIP anda sebagai responden atau Server(SIMPEG) sedang maintenance mohon Menunggu beberapa saat, <br/><br/> Terima Kasih</h5></div>
			</div>
			
			<p class="mt-5 h5">Quick Access</p>
			<div class="card ">
			    <!-- <button class=" btn btn-info btn-lg btn-block">PEMETAAAN</button> -->
			    <a class="btn btn-info btn-lg btn-block" href="${pageContext.request.contextPath}/page/dashboard?mode=profile&"><i class="fas fa-fw fa-tachometer-alt"></i> DASHBOARD PEMETAAN</a>
			</div>
         </c:when>
         <c:when test = "${requestScope.browser.name != 'Chrome'}">
	        <div class="card mb-3">
			    <div class="card-body"><h4 class="text-justify">Sistem mendeteksi anda menggunakan browser selain <strong>chrome</strong>, Mohon pastikan anda telah menggunakan google chrome sebagai browser/peramban anda, untuk dapat mengakses <span class="text-success">SPeKtra</span>.<br/></br> <strong>Terima Kasih</strong></h4></div>
			</div>
         </c:when>
         
         <c:otherwise>
			<form id="form-entri">
		    <div class="card ">
			  <div class="card-header">
				<h6 class="card-title p-0 m-0">Informasi Profil Pegawai</h6>
			  </div>
			  <div class="card-body">
			    <!-- <h5 class="card-title">Special title treatment</h5>
			    <p class="card-text">With supporting text below as a natural lead-in to additional content.</p> -->
				  <div class="form-group row">
				    <label for="" class="col-sm-2 col-form-label text-md-right">NIP</label>
				    <div class="col-sm-6">
				      <input name="nip" type="text" class="form-control" value="${requestScope.nip}" readonly>
				    </div>
				  </div>
				  <div class="form-group row">
				    <label for="" class="col-sm-2 col-form-label text-md-right">Nama</label>
				    <div class="col-sm-6">
				      <input name="nama" type="text" class="form-control" value="${requestScope.nama}" readonly>
				    </div>
				    <div class="col-sm-2">
			      		<c:choose>
				         <c:when test = "${requestScope.idEselon1 == 100 or requestScope.golongan eq null or requestScope.golongan eq ''}">
				         	<select name="golongan" class="form-control">
								<option value="">Pilih Gol</option>
				         	</select>
				         </c:when>
				         <c:otherwise>
				         	<input name="golongan" type="text" class="form-control" value="${requestScope.golongan}" readonly>
				         </c:otherwise>
				         </c:choose>
				    </div>
				  </div>
				  <div class="form-group row">
				    <label for="" class="col-sm-2 col-form-label text-md-right">Eselon1</label>
				    <div class="col-sm-8">
				      <select name="id_eselon1" class="form-control" onchange="getSatker()">
				      <c:choose>
				      	<c:when test="${requestScope.idEselon1 == 100}">
				      		<option value="${requestScope.idEselon1}">${requestScope.eselon1}</option>
				      	</c:when>
				      	<c:otherwise>
					      	<c:if test="${requestScope.eselon1New.size() > 1}">
								<option value="">Pilih Salah Satu</option>
							</c:if>
					     	<c:forEach items="${requestScope.eselon1New}" var="k" varStatus="loopStatus">
								<c:if test="${!fn:contains(k.nama, 'delete')}">
									<option value="${k.id}">${k.nama}</option>
								</c:if>
					      	</c:forEach>
				      	</c:otherwise>
				      </c:choose>
				      </select>
				    </div>
				  </div>
				  <div class="form-group row">
				    <label for="" class="col-sm-2 col-form-label text-md-right">Satuan Kerja</label>
				    <div class="col-sm-8">
				      <select name="id_unit_kerja" class="form-control">
				      	<%-- <option value="${requestScope.idUnitKerjaNew}">${requestScope.unitKerjaNew}</option> --%>
			      		<c:if test="${requestScope.idEselon1 == 100}">
			      			<option value="${requestScope.idSatker}">${requestScope.namaSatker}</option>
			      		</c:if>
				      	<c:if test="${requestScope.idEselon1 != 100}">
				      		<option value="">-</option>
					      	<%-- <c:if test="${requestScope.idSatkerNew.size() > 1}">
								<option value="">Pilih Salah Satu</option>
							</c:if> --%>
							<%-- <c:set value="${requestScope.namaSatker}" var="namaSatker" />
							<c:forEach items="${requestScope.idSatkerNew}" var="k" varStatus="loopStatus">
								<option value="${k.idUnitAuditi}">${k.namaUnitAuditi}</option>
							</c:forEach> --%>
					  	</c:if>
				      </select>
					  <select name="id_propinsi" class="d-none">
					    <c:if test="${requestScope.idPropinsi != null}">
				      		<option value="${requestScope.idPropinsi}">${requestScope.idPropinsi}</option>
				      	</c:if>
		      		  </select>
				    </div>
				  </div>
				  <div class="form-group row">
				    <label for="" class="col-sm-2 col-form-label text-md-right">Jabatan</label>
				    <div class="col-sm-8">
				      <input type="text" class="form-control" value="${requestScope.jabatan}" readonly>
				    </div>
				  </div>
				  <div class="form-group row">
				    <label for="" class="col-sm-2 col-form-label text-md-right">Jenis Kelamin</label>
				    <div class="col-sm-4">
				      <input name="jenis_kelamin" type="text" class="form-control" value="${requestScope.jenisKelamin}" readonly>
				    </div>
				     <div class="col-sm-4">
				      <input value="${requestScope.tanggalLahir}" id="tanggal_lahir" name="tanggal_lahir" type="date" class="form-control" placeholder="Tentukan Tgl.Lahir Anda">
				    </div>
				   <!--  <script>
				    	document.getElementById("tanggal_lahir").value = "2014-02-09";
				    </script> -->
				  </div>
				  <small class="card-title text-primary">TIPS: Apabila Kolom <strong>Eselon1, Satker, dan Jabatan</strong> anda tidak sesuai, silahkan hubungi admin.</small>
				  
			  </div>
			</div>
	        <div class="card mt-3 mb-3">
				<div class="card-header "><h6 class="card-title p-0 m-0">Klarifikasi Bidang Teknis dan Jabatan Anda :</h6></div>
			 	<div class="card-body">
				  <div class="form-group row d-none">
				    <label for="" class="col-sm-2 col-form-label text-md-right">RESPONDEN</label>
				    <div class="col-sm-4">
				      <input type="text" class="form-control" name="id_responden" value="${requestScope.idResponden}" readonly>
				    </div>
				    <div class="col-sm-4">
				      <input type="text" class="form-control" name="id_sesi" value="${requestScope.idSesi}" readonly>
				    </div>
				  </div>
				  <div class="row form-group d-nones">
				  	<label for="" class="col-sm-2 col-form-label text-md-right">Jabatan</label>
				    <div class="col-sm-8">
				      <select name="id_bidang_teknis" class="form-control" onchange="getSelectJabatan(this);" >
				      	<option value="">Pilih</option>
				      	<c:forEach items="${requestScope.listBidangTeknis}" var="k" varStatus="loopStatus">
						<option value="${k.id}" data-idjabatan="${k.idKelompokJabatan}">${k.nama}</option>	
					  	</c:forEach>
				      </select>
				    </div>
				  </div>
				  <div class="row form-group ">
				  	<label for="" class="col-sm-2 col-form-label text-md-right">Jenjang</label>
				    <div class="col-sm-8">
				      <select name="id_jabatan" class="form-control form-control-lg select select2">
				      	<%-- <c:forEach items="${requestScope.listMasterJabatan}" var="k" varStatus="loopStatus">
						<option value="${k.id}">${k.nama}</option>	
					  	</c:forEach> --%>
				      </select>
				    </div>
				  </div>
				  <small class="card-title text-primary">TIPS: Apabila Kolom <strong>Jabatan</strong> atau <strong>Jenjang</strong> anda tidak muncul, coba lakukan refresh(CTRL+F5) atau logout, kemudian coba login kembali.</small>
				  
				</div>
			  	<div class="card-footer ">
				<button type="submit" class="btn btn-success float-right">Selanjutnya</button>
				</div>
			</div>
			</form>
         </c:otherwise>
      </c:choose>
		
    </div>
	
	</div>
	</div>
	<script src="${pageContext.request.contextPath}/js/general-index-script.js"></script>
	<%@include file="inc/footer.jsp"%>
</body>

</html>